### ISSUE TITLE
.opml file support

### ISSUE THREAD

**Issue by ZamanOof** [Findus23/rss2wallabag#46]
is possible to use .opml file
thanks

**Comment by Findus23** [comment]
Hi,

OPML is a pretty simple format, so you should be able to write a small program that fetches the list of feeds from the file and outputs it in the yaml format used here.
See here for an example file:
http://hosting.opml.org/dave/spec/subscriptionList.opml
and here for the documentation:
http://opml.org/spec2.opml

If the file isn't too long, you should also be able to do it with a bit of copy and paste manually.
