### ISSUE TITLE
output whole content of the article instead of just links

### ISSUE THREAD

**Issue by extr15** [Findus23/rss2wallabag#47]
Hi, thanks for your work.
I have a rss feed which including articles' link and content, however sometimes the link may be broken later, thus I can not get the content from the link in wallabag. Could you output the existing article content from rss feed to wallabag instead of just article link?

**Comment by Findus23** [comment]
I am not even sure if it is possible to send HTML to wallabag for the article:
https://app.wallabag.it/api/doc#post--api-entries.{_format}

Also this would circumvent all of the tricks wallabag uses to get a readable version of the HTML and means you could use any other RSS reader instead.

**Comment by extr15** [comment]
Thanks, I made a quick test and it worked to post the `content` parameter to wallabag even if the url is bad.
```
data["url"] = "bad/link"
data["content"] = "some string content"
r = self.s.post(self.host + "/api/entries.json", data=data, headers=self.auth_headers)
```

**Comment by Findus23** [comment]
Thanks for the notice. Seems like I totally missed the `content` parameter.
